"""Implement layered architecture and autoclose setup

Revision ID: 2bab4dc4cf1d
Revises: defcd57a3259
Create Date: 2025-11-30 22:21:51.201407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bab4dc4cf1d'
down_revision: Union[str, Sequence[str], None] = 'defcd57a3259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
