"""Add closed_at to Task model and implement service/repo structure

Revision ID: defcd57a3259
Revises: 085021ba6daa
Create Date: 2025-11-30 22:16:04.899209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'defcd57a3259'
down_revision: Union[str, Sequence[str], None] = '085021ba6daa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
